test:
	python import_csv.py departments
	python import_csv.py people
	python import_csv.py positions
	python import_csv.py articles
	python import_csv.py authors


pep:
	flake8 import_csv.py
	flake8 template_graph.py
